/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeWorkbook {
  get closed(): boolean
  close(): void
  summary(): NativeWorkbookSummary
  readRange(sheet: string, start: string, end: string, offset: number, limit: number): NativeRangePage
  functionUsage(): NativeFunctionUsageReport
  calculate(todaySerial?: number | undefined | null, nowSerial?: number | undefined | null, arithmeticSemantics?: string | undefined | null, financialSolverSemantics?: string | undefined | null): Promise<NativeCalculationReport>
  recalculate(mode: string, todaySerial?: number | undefined | null, nowSerial?: number | undefined | null, arithmeticSemantics?: string | undefined | null, financialSolverSemantics?: string | undefined | null): Promise<NativeCalculationDelta>
  applyChanges(expectedRevision: string, batchJson: string): NativeEditReceipt
  changesSince(cursor: string, limit: number): NativeCalculationDeltaPage
  cancelCalculation(): boolean
  calculationActive(): boolean
  setBlank(sheet: string, address: string): void
  setNumber(sheet: string, address: string, value: number): void
  setText(sheet: string, address: string, value: string): void
  setLogical(sheet: string, address: string, value: boolean): void
  setError(sheet: string, address: string, value: string): void
  setFormula(sheet: string, address: string, formula: string, dynamicRange?: string | undefined | null): void
  clearCell(sheet: string, address: string): boolean
  addSheet(name: string): number
  renameSheet(currentName: string, newName: string): void
  toBytes(invalidateUnavailable: boolean): Promise<Buffer>
  savePath(path: string, invalidateUnavailable: boolean, replaceExisting: boolean): Promise<NativeWriteReport>
}

export declare function createWorkbook(): NativeWorkbook

export interface NativeCalculationDelta {
  schemaVersion: number
  cursor: string
  baseRevision: string
  resultRevision: string
  mode: string
  reason: string
  dirtyCount: number
  evaluatedCount: number
  parsedFormulaCount: number
  changedCells: Array<NativeCalculationDeltaCell>
  removedMaterializedCells: Array<NativeCellReference>
}

export interface NativeCalculationDeltaCell {
  cell: NativeCellReference
  origin: string
  anchor?: NativeCellReference
  range?: string
  result: NativeCalculationResult
}

export interface NativeCalculationDeltaPage {
  schemaVersion: number
  requestedCursor: string
  nextCursor?: string
  deltas: Array<NativeCalculationDelta>
}

export interface NativeCalculationReport {
  schemaVersion: number
  semanticRevision: string
  formulaCount: number
  valueCount: number
  unavailableCount: number
  materializedCellCount: number
}

export interface NativeCalculationResult {
  kind: string
  value?: NativeCellValue
  code?: string
  message?: string
  detail?: string
}

export interface NativeCell {
  address: string
  formula?: string
  sourceValue: NativeCellValue
  sourceValueState: string
  calculated?: NativeCalculationResult
}

export interface NativeCellReference {
  sheetId: number
  sheetName: string
  address: string
}

export interface NativeCellValue {
  kind: string
  numberValue?: number
  textValue?: string
  logicalValue?: boolean
  errorValue?: string
}

export interface NativeEditReceipt {
  schemaVersion: number
  baseRevision: string
  resultRevision: string
  appliedChangeCount: number
  changedCells: Array<NativeCellReference>
  calculationChangedCells: Array<NativeCellReference>
  createdSheetIds: Array<number>
  topologyChanged: boolean
  calculationMetadataChanged: boolean
}

export interface NativeFunctionUsageEntry {
  name: string
  supported: boolean
  callCount: number
  formulaCount: number
  sampleCells: Array<NativeCellReference>
}

export interface NativeFunctionUsageReport {
  schemaVersion: number
  formulaCount: number
  parsedFormulaCount: number
  unparsedFormulaCount: number
  entries: Array<NativeFunctionUsageEntry>
}

export interface NativeRangePage {
  schemaVersion: number
  sheet: string
  start: string
  end: string
  totalCells: number
  offset: number
  nextOffset?: number
  cells: Array<NativeCell>
}

export interface NativeSheetSummary {
  id: number
  name: string
  visibility: string
  cellCount: number
  usedRange?: string
}

export interface NativeWorkbookSummary {
  schemaVersion: number
  semanticRevision: string
  documentBacked: boolean
  documentKind: string
  dateSystem: string
  diagnosticCount: number
  sheets: Array<NativeSheetSummary>
}

export interface NativeWriteReport {
  schemaVersion: number
  complete: boolean
  policy: string
  materializedCount: number
  invalidatedCells: Array<NativeCellReference>
  changedParts: Array<string>
  removedParts: Array<string>
  diagnosticCount: number
}

export declare function openWorkbookBytes(bytes: Buffer): Promise<NativeWorkbook>

export declare function openWorkbookPath(path: string): Promise<NativeWorkbook>

export declare function schemaVersion(): number
